build: off
test: off
deploy: off

environment:
  FUNQ_MAKE_PATH: "mingw32-make"
  FUNQ_CXXFLAGS: "-Wall -Wextra -Werror"  # make CI fail on warnings
  matrix:
    # Test with oldest Qt version available on AppVeyor
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      QT_DIR: C:/Qt/5.3/mingw482_32
      MINGW_DIR: C:/Qt/Tools/mingw482_32
    # Test with latest Qt LTS version
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QT_DIR: C:/Qt/5.12/mingw73_32
      MINGW_DIR: C:/Qt/Tools/mingw730_32
    # Test with latest Qt version available on AppVeyor
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT_DIR: C:/Qt/5.15/mingw81_32
      MINGW_DIR: C:/Qt/Tools/mingw810_32

init:
  - set PATH=%QT_DIR%/bin;%MINGW_DIR%/bin;%PATH%

install:
  - cd client && python setup.py develop && cd ..
  - cd server && python setup.py develop && cd ..
  - cd server/tests && qmake QMAKE_CXXFLAGS="%FUNQ_CXXFLAGS%" && mingw32-make -j4 && cd ../../
  - cd tests-functionnal/funq-test-app && qmake QMAKE_CXXFLAGS="%FUNQ_CXXFLAGS%" && mingw32-make -j4 && cd ../..

build_script:
  - cd client && python setup.py test && cd ..
  - mingw32-make -C server/tests/ check
  - cd tests-functionnal && nosetests && cd ..
