os: Windows Server 2012
build: off
test: off
deploy: off

init:
  - set PATH=C:/Qt/5.11/mingw53_32/bin;C:/Qt/Tools/mingw530_32/bin;%PATH%

install:
  - cp C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe C:/Qt/Tools/mingw530_32/bin/make.exe
  - cd client && python setup.py develop && cd ..
  - cd server && python setup.py develop && cd ..
  - cd server/tests && qmake && make -j4 && cd ../../
  - cd tests-functionnal/funq-test-app && qmake && make -j4 && cd ../..

build_script:
  - cd client && python setup.py test && cd ..
  - make -C server/tests/ check
  - cd tests-functionnal
  # run tests multiple times to also catch sporadic errors
  - nosetests
  - nosetests
  - nosetests
  - nosetests
  - nosetests
  - nosetests
  - nosetests
  - nosetests
  - nosetests
  - nosetests

on_failure:
  - appveyor PushArtifact log.txt
